# Generated by Django 5.1.6 on 2025-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter member's first name", max_length=35)),
                ('last_name', models.CharField(help_text="Enter member's last name", max_length=35)),
                ('email_addr', models.EmailField(help_text='Provide a valid email address', max_length=254, unique=True)),
                ('phone_num', models.CharField(help_text='Enter a phone number in format: (ex: 123-456-7890)', max_length=16)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('reg', 'Regular')], default='reg', help_text="Select member's role (Admin or Regular Member)", max_length=16)),
            ],
        ),
    ]
