# Generated by Django 5.1.6 on 2025-02-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='email_addr',
            new_name='email',
        ),
    ]
