# Generated by Django 5.1.6 on 2025-02-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_rename_phone_num_teammember_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular')], default='regular', help_text="Select member's role (Admin or Regular Member)", max_length=16),
        ),
    ]
